### ISSUE TITLE
Assignment 1 is undone.!

### ISSUE THREAD

**Issue by Ashok-1999** [kambleaa007/ReactCoursera#1]
The comments won't change according to the on click function.

**Comment by kambleaa007** [comment]
can you tell more about the issue and reproduction steps,
Thanks for your time

**Comment by Ashok-1999** [comment]
it works fine, sorry about that,
and just remove  className="row"  line 82 in [https://github.com/kambleaa007/ReactCoursera/blob/master/one/confusion/src/components/MenuComponent.js](url)

to make it align perfectly.
